const csc124Questions = [
  { q: "A computer network is best defined as:", opts: ["A single computer with many files", "Two or more interconnected devices that share resources", "A software package for communication", "A cable system only"], ans: 1 },
  { q: "Which of the following is an example of a node in networking?", opts: ["Printer", "Router", "Computer", "All of the above"], ans: 3 },
  { q: "A communication path connecting two nodes is called:", opts: ["Protocol", "Link", "Port", "Layer"], ans: 1 },
  { q: "A set of rules governing communication between devices is called:", opts: ["Standard", "Protocol", "Address", "Packet"], ans: 1 },
  { q: "Bandwidth is measured in:", opts: ["Bytes", "Bits per second", "Hertz only", "Volt"], ans: 1 },
  { q: "Which company is an ISP in Nigeria?", opts: ["MTN", "HP", "Dell", "Lenovo"], ans: 0 },
  { q: "PAN means:", opts: ["Public Area Network", "Personal Area Network", "Private Access Network", "Packet Area Network"], ans: 1 },
  { q: "LAN covers:", opts: ["Large country", "Small local area", "Entire world", "Ocean cable"], ans: 1 },
  { q: "WAN stands for:", opts: ["Wide Area Network", "Wireless Area Node", "Web Access Network", "Wide Access Node"], ans: 0 },
  { q: "The earliest major computer network was:", opts: ["Bluetooth", "ARPANET", "Ethernet", "GSM"], ans: 1 },
  { q: "The OSI model contains:", opts: ["4 layers", "5 layers", "7 layers", "8 layers"], ans: 2 },
  { q: "Which layer is responsible for physical transmission?", opts: ["Physical Layer", "Network Layer", "Session Layer", "Transport Layer"], ans: 0 },
  { q: "Which OSI layer handles MAC addresses?", opts: ["Physical", "Data Link", "Transport", "Session"], ans: 1 },
  { q: "Routers operate mainly at:", opts: ["Layer 1", "Layer 2", "Layer 3", "Layer 7"], ans: 2 },
  { q: "Switches operate at:", opts: ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], ans: 1 },
  { q: "The PDU at Layer 3 is called:", opts: ["Frame", "Packet", "Segment", "Bit"], ans: 1 },
  { q: "The PDU at Layer 2 is:", opts: ["Frame", "Packet", "Segment", "Signal"], ans: 0 },
  { q: "TCP is:", opts: ["Connectionless", "Reliable", "Unreliable", "Wireless only"], ans: 1 },
  { q: "UDP is:", opts: ["Reliable", "Connection-oriented", "Fast and connectionless", "Physical medium"], ans: 2 },
  { q: "HTTP uses default port:", opts: ["21", "25", "80", "443"], ans: 2 },
  { q: "HTTPS uses port:", opts: ["80", "110", "443", "53"], ans: 2 },
  { q: "DNS uses port:", opts: ["53", "21", "22", "143"], ans: 0 },
  { q: "IPv4 address contains:", opts: ["16 bits", "32 bits", "64 bits", "128 bits"], ans: 1 },
  { q: "IPv6 contains:", opts: ["32 bits", "64 bits", "128 bits", "256 bits"], ans: 2 },
  { q: "CIDR notation /24 means:", opts: ["24 host bits", "24 network bits", "24 subnet devices", "24 routers"], ans: 1 },
  { q: "DHCP is used to:", opts: ["Encrypt traffic", "Assign IP addresses automatically", "Detect viruses", "Switch packets"], ans: 1 },
  { q: "DNS converts:", opts: ["IP to MAC", "Domain names to IP addresses", "MAC to IP", "Signals to packets"], ans: 1 },
  { q: "The TCP/IP model has:", opts: ["3 layers", "4 layers", "5 layers", "7 layers"], ans: 1 },
  { q: "The top TCP/IP layer is:", opts: ["Internet", "Application", "Transport", "Access"], ans: 1 },
  { q: "Noise affects:", opts: ["Signal quality", "File names", "Keyboard speed", "Printer ink"], ans: 0 },
  { q: "Nyquist theorem relates to:", opts: ["Sampling", "Routing", "Switching", "Firewall"], ans: 0 },
  { q: "Manchester encoding is used in:", opts: ["Ethernet", "Satellite TV", "Modem typing", "Printer"], ans: 0 },
  { q: "FM means:", opts: ["Frequency Modulation", "Fast Modulation", "Frame Method", "Frequency Method"], ans: 0 },
  { q: "AM means:", opts: ["Analog Method", "Amplitude Modulation", "Access Medium", "Active Memory"], ans: 1 },
  { q: "QAM stands for:", opts: ["Quick Access Mode", "Quadrature Amplitude Modulation", "Queue Access Modulation", "Quality Analog Method"], ans: 1 },
  { q: "FDM means:", opts: ["Frequency Division Multiplexing", "Fast Data Medium", "Fibre Digital Method", "Full Duplex Mode"], ans: 0 },
  { q: "TDM means:", opts: ["Time Division Multiplexing", "Transfer Data Method", "Topology Device Method", "Terminal Data Multiplex"], ans: 0 },
  { q: "CRC is mainly used for:", opts: ["Error detection", "Addressing", "Encryption", "Routing"], ans: 0 },
  { q: "Star topology uses:", opts: ["Central switch", "Backbone cable only", "Circular connection", "No central device"], ans: 0 },
  { q: "Bus topology uses:", opts: ["Central router", "Backbone cable", "Fibre ring", "Wireless hub"], ans: 1 },
  { q: "Ring topology passes data in:", opts: ["Straight line", "Circular path", "Mesh pattern", "Random form"], ans: 1 },
  { q: "Mesh topology advantage is:", opts: ["Cheap cost", "High redundancy", "Easy wiring", "Low security"], ans: 1 },
  { q: "Hybrid topology combines:", opts: ["Only wireless", "Two or more topologies", "Only star", "Only bus"], ans: 1 },
  { q: "IEEE developed:", opts: ["IPv4", "Ethernet standards", "HTTP", "Linux"], ans: 1 },
  { q: "IEEE 802.3 refers to:", opts: ["Wi-Fi", "Ethernet", "Bluetooth", "VLAN only"], ans: 1 },
  { q: "IEEE 802.11 refers to:", opts: ["Ethernet", "Wi-Fi", "Fibre", "Router"], ans: 1 },
  { q: "ISO is known for:", opts: ["TCP only", "OSI model", "Firewall", "Modem"], ans: 1 },
  { q: "IETF manages:", opts: ["RFC standards", "Fibre cables", "Hardware assembly", "LAN cards"], ans: 0 },
  { q: "Packet switching is used by:", opts: ["Telephone voice only", "Internet", "Printer cable", "Radio only"], ans: 1 },
  { q: "Circuit switching requires:", opts: ["Dedicated path", "Shared packet route", "Random signal", "No setup"], ans: 0 },
  { q: "Which device connects multiple computers in a LAN?", opts: ["Modem", "Switch", "Repeater", "Firewall"], ans: 1 },
  { q: "A hub works at which OSI layer?", opts: ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], ans: 0 },
  { q: "A switch forwards data using:", opts: ["IP address", "MAC address", "Port number", "Domain name"], ans: 1 },
  { q: "A router forwards packets using:", opts: ["MAC address", "IP address", "Signal strength", "Port cable"], ans: 1 },
  { q: "A repeater is used to:", opts: ["Encrypt packets", "Regenerate weak signals", "Assign IP address", "Store files"], ans: 1 },
  { q: "A bridge connects:", opts: ["Two different networks", "Two LAN segments", "Internet only", "Wireless stations only"], ans: 1 },
  { q: "A gateway mainly:", opts: ["Connects different protocols", "Boosts signals", "Stores packets", "Measures speed"], ans: 0 },
  { q: "NIC means:", opts: ["Network Interface Card", "Network Internet Control", "Node Interface Cable", "Network Internal Channel"], ans: 0 },
  { q: "Each NIC has a unique:", opts: ["Port number", "MAC address", "IP protocol", "Domain ID"], ans: 1 },
  { q: "MAC address length is:", opts: ["16 bits", "32 bits", "48 bits", "64 bits"], ans: 2 },
  { q: "A MAC address is written in:", opts: ["Decimal", "Binary only", "Hexadecimal", "Roman numerals"], ans: 2 },
  { q: "Which device converts digital to analog signals?", opts: ["Switch", "Modem", "Router", "Hub"], ans: 1 },
  { q: "Modem means:", opts: ["Modify-Demodify", "Modulate-Demodulate", "Mode-Decode", "Module-Digital"], ans: 1 },
  { q: "UTP stands for:", opts: ["Unshielded Twisted Pair", "Universal Twisted Port", "Unified Transfer Pair", "Upper Twisted Protocol"], ans: 0 },
  { q: "Which cable is commonly used in Ethernet LAN?", opts: ["Coaxial", "UTP", "Fibre only", "USB"], ans: 1 },
  { q: "RJ45 connector is used with:", opts: ["Fibre cable", "UTP cable", "Coaxial cable", "Serial cable"], ans: 1 },
  { q: "A straight-through cable connects:", opts: ["Same devices", "Different devices", "Fibre only", "Wireless systems"], ans: 1 },
  { q: "A crossover cable connects:", opts: ["Different devices", "Same devices", "Modem only", "Router to ISP only"], ans: 1 },
  { q: "Fibre optic cable transmits data using:", opts: ["Electricity", "Light", "Magnetism", "Sound"], ans: 1 },
  { q: "Which cable has highest speed?", opts: ["UTP", "Coaxial", "Fibre optic", "Telephone cable"], ans: 2 },
  { q: "Coaxial cable has:", opts: ["Single copper core", "Two twisted wires", "Glass strands only", "Plastic core only"], ans: 0 },
  { q: "Transmission through air is called:", opts: ["Guided media", "Unguided media", "Optical media", "Copper media"], ans: 1 },
  { q: "Microwave transmission requires:", opts: ["Underground path", "Line of sight", "Water medium", "Copper tube"], ans: 1 },
  { q: "Infrared is used for:", opts: ["Satellite only", "Short-range communication", "Ocean cable", "Telephone exchange"], ans: 1 },
  { q: "Bluetooth belongs to:", opts: ["WAN", "PAN", "MAN", "SAN"], ans: 1 },
  { q: "Wi-Fi standard is:", opts: ["IEEE 802.3", "IEEE 802.11", "IEEE 802.5", "IEEE 802.1"], ans: 1 },
  { q: "CSMA/CD is mainly used in:", opts: ["Ethernet", "Bluetooth", "Satellite", "Telephone"], ans: 0 },
  { q: "CSMA/CD helps to:", opts: ["Detect collisions", "Encrypt data", "Assign IP", "Store files"], ans: 0 },
  { q: "Full duplex means:", opts: ["Send only", "Receive only", "Send and receive simultaneously", "Send twice"], ans: 2 },
  { q: "Half duplex means:", opts: ["Send and receive at same time", "Send and receive one at a time", "Receive only", "No communication"], ans: 1 },
  { q: "Simplex communication means:", opts: ["Two-way communication", "One-way communication", "Simultaneous transmission", "Internet sharing"], ans: 1 },
  { q: "An example of simplex device is:", opts: ["Telephone", "Radio broadcast", "WhatsApp", "Switch"], ans: 1 },
  { q: "Which topology has the highest fault tolerance?", opts: ["Bus", "Star", "Mesh", "Ring"], ans: 2 },
  { q: "Token passing is associated with:", opts: ["Ring topology", "Bus topology", "Star topology", "Mesh topology"], ans: 0 },
  { q: "A server is:", opts: ["Client machine only", "Computer providing services", "Router cable", "Signal amplifier"], ans: 1 },
  { q: "A client is:", opts: ["Device requesting service", "Main server", "Router", "Hub"], ans: 0 },
  { q: "Peer-to-peer network means:", opts: ["No server involved", "One main server only", "Satellite communication", "Internet routing only"], ans: 0 },
  { q: "Which is more secure?", opts: ["Open Wi-Fi", "WPA2", "No password", "Public hotspot"], ans: 1 },
  { q: "WPA stands for:", opts: ["Wireless Protected Access", "Web Protected Access", "Wireless Packet Access", "Wide Protocol Access"], ans: 0 },
  { q: "SSID means:", opts: ["Secure Signal ID", "Service Set Identifier", "System Security Internet Data", "Signal Server Interface Device"], ans: 1 },
  { q: "Firewall is used for:", opts: ["Cooling systems", "Security filtering", "Cable joining", "File compression"], ans: 1 },
  { q: "Antivirus protects against:", opts: ["Hardware damage", "Malware", "Router failure", "Signal noise"], ans: 1 },
  { q: "Phishing is:", opts: ["Cable theft", "Fake attempt to steal information", "Wireless connection", "File backup"], ans: 1 },
  { q: "Malware includes:", opts: ["Virus", "Worm", "Trojan", "All of the above"], ans: 3 },
  { q: "A worm spreads:", opts: ["Through food", "Across networks automatically", "By printing", "Through keyboard"], ans: 1 },
  { q: "A Trojan appears as:", opts: ["Genuine software", "Cable error", "Router damage", "Hardware fault"], ans: 0 },
  { q: "The strongest password should contain:", opts: ["Only letters", "Letters, numbers and symbols", "Only numbers", "Username only"], ans: 1 },
  { q: "Encryption is used to:", opts: ["Hide information", "Increase speed", "Delete files", "Format cable"], ans: 0 },
  { q: "Which protocol is secure?", opts: ["HTTP", "HTTPS", "FTP", "Telnet"], ans: 1 },
  { q: "VPN means:", opts: ["Virtual Private Network", "Verified Public Node", "Virtual Packet Network", "Variable Private Node"], ans: 0 },
  { q: "Which protocol is used to send emails?", opts: ["HTTP", "SMTP", "FTP", "DNS"], ans: 1 },
  { q: "Which protocol is used to receive emails?", opts: ["SMTP", "FTP", "IMAP", "ARP"], ans: 2 },
  { q: "POP3 is used for:", opts: ["Sending emails", "Receiving emails", "Routing packets", "Encrypting data"], ans: 1 },
  { q: "FTP is used for:", opts: ["Email transfer", "File transfer", "Web browsing", "Network routing"], ans: 1 },
  { q: "Telnet is used for:", opts: ["Secure connection", "Remote login", "Email sending", "File encryption"], ans: 1 },
  { q: "SSH is preferred over Telnet because it is:", opts: ["Faster", "More secure", "Cheaper", "Simpler"], ans: 1 },
  { q: "HTTP stands for:", opts: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyper Transfer Tool Protocol", "Host Transfer Text Process"], ans: 0 },
  { q: "HTTPS provides:", opts: ["Faster browsing", "Secure communication", "Free internet", "Signal boost"], ans: 1 },
  { q: "A web browser is:", opts: ["Hardware device", "Application software", "Network cable", "Protocol"], ans: 1 },
  { q: "Example of a web browser:", opts: ["Windows", "Chrome", "Linux", "Router"], ans: 1 },
  { q: "A URL represents:", opts: ["IP address", "Web address", "MAC address", "Network cable"], ans: 1 },
  { q: "DNS resolves:", opts: ["MAC to IP", "Domain name to IP", "IP to MAC", "Signal to packet"], ans: 1 },
  { q: "The Internet is:", opts: ["A single computer", "A global network of networks", "A LAN", "A modem system"], ans: 1 },
  { q: "Packet switching divides data into:", opts: ["Frames only", "Small packets", "Signals only", "Voltages"], ans: 1 },
  { q: "Routing is the process of:", opts: ["Sending signals randomly", "Finding path for data", "Encrypting data", "Compressing files"], ans: 1 },
  { q: "A routing table contains:", opts: ["File names", "Paths to networks", "Passwords", "Email lists"], ans: 1 },
  { q: "Static routing means:", opts: ["Routes change automatically", "Routes are manually configured", "Routes do not exist", "Wireless routing"], ans: 1 },
  { q: "Dynamic routing means:", opts: ["Manual routing", "Automatic route updates", "No routing", "Fixed paths"], ans: 1 },
  { q: "A hop is:", opts: ["Cable type", "One step between routers", "Data packet", "Signal type"], ans: 1 },
  { q: "Traceroute is used to:", opts: ["Test speed", "Show path taken by packets", "Encrypt data", "Send emails"], ans: 1 },
  { q: "Ping command is used to:", opts: ["Check connectivity", "Send files", "Route traffic", "Encrypt packets"], ans: 0 },
  { q: "Latency refers to:", opts: ["Data size", "Delay in transmission", "Signal strength", "Cable length"], ans: 1 },
  { q: "Throughput is:", opts: ["Maximum capacity", "Actual data rate", "Voltage", "Frequency"], ans: 1 },
  { q: "Jitter affects:", opts: ["File storage", "Voice/video quality", "Router speed", "Cable size"], ans: 1 },
  { q: "Packet loss means:", opts: ["Data duplication", "Lost packets", "Signal increase", "Faster transmission"], ans: 1 },
  { q: "Cloud computing provides:", opts: ["Physical hardware only", "Services over the internet", "Only LAN access", "Cable connection"], ans: 1 },
  { q: "SaaS means:", opts: ["Software as a Service", "System as a Signal", "Server as a Software", "Software as a System"], ans: 0 },
  { q: "IaaS provides:", opts: ["Applications only", "Infrastructure services", "Email services", "Browser tools"], ans: 1 },
  { q: "PaaS means:", opts: ["Platform as a Service", "Packet as a System", "Protocol as a Server", "Platform as a Signal"], ans: 0 },
  { q: "IoT stands for:", opts: ["Internet of Tools", "Internet of Things", "Input of Technology", "Internal of Transmission"], ans: 1 },
  { q: "IoT devices include:", opts: ["Smart bulbs", "Sensors", "Smart TVs", "All of the above"], ans: 3 },
  { q: "5G technology offers:", opts: ["Low speed", "High latency", "High speed and low latency", "No connectivity"], ans: 2 },
  { q: "VoIP means:", opts: ["Voice over IP", "Video over Internet Port", "Voice on Internal Protocol", "Virtual Output Input Process"], ans: 0 },
  { q: "SIP is used for:", opts: ["File transfer", "Call setup", "Email sending", "Routing"], ans: 1 },
  { q: "RTP is used for:", opts: ["Real-time media transmission", "Routing", "DNS lookup", "Encryption"], ans: 0 },
  { q: "Firewall protects against:", opts: ["Hardware failure", "Unauthorized access", "Signal loss", "Cable break"], ans: 1 },
  { q: "VPN provides:", opts: ["Public browsing", "Secure private connection", "Faster internet only", "Free Wi-Fi"], ans: 1 },
  { q: "Authentication verifies:", opts: ["Data speed", "Identity", "Signal strength", "Cable type"], ans: 1 },
  { q: "Authorization determines:", opts: ["Identity", "Access level", "Signal strength", "Packet size"], ans: 1 },
  { q: "Accounting tracks:", opts: ["User activities", "Signal power", "Cable length", "Device speed"], ans: 0 },
  { q: "AAA stands for:", opts: ["Authentication, Authorization, Accounting", "Access, Address, Allocation", "Analog, Amplify, Assign", "Application, Access, Address"], ans: 0 },
  { q: "Encryption converts data into:", opts: ["Plain text", "Cipher text", "Packet format", "Frame format"], ans: 1 },
  { q: "Decryption converts:", opts: ["Cipher text to plain text", "Plain text to cipher", "Packet to signal", "Signal to packet"], ans: 0 },
  { q: "Symmetric encryption uses:", opts: ["Two keys", "One key", "No key", "Public key only"], ans: 1 },
  { q: "Asymmetric encryption uses:", opts: ["One key", "Two keys", "No key", "Same key"], ans: 1 },
  { q: "A digital signature ensures:", opts: ["Speed", "Authentication and integrity", "Signal strength", "Routing"], ans: 1 },
  { q: "Network security aims to:", opts: ["Slow network", "Protect data and systems", "Increase cost", "Reduce speed"], ans: 1 },
  { q: "Backup is used for:", opts: ["Speed increase", "Data recovery", "Signal improvement", "Routing"], ans: 1 },
  { q: "Disaster recovery ensures:", opts: ["Fast internet", "Business continuity", "Cable repair", "Signal boost"], ans: 1 },
  { q: "A network administrator is responsible for:", opts: ["Playing games", "Managing network systems", "Watching videos", "Writing music"], ans: 1 }
];
