const csc122Questions = [
  { q: "A complete electric circuit must contain:", opts: ["Only a battery", "Only a load", "A source, load, and conducting path", "Only wires"], ans: 2 },
  { q: "The main function of a voltage source is to:", opts: ["Store energy", "Provide electrical pressure", "Reduce resistance", "Block current"], ans: 1 },
  { q: "Which of the following is an example of a load?", opts: ["Battery", "Wire", "Lamp", "Switch"], ans: 2 },
  { q: "Voltage is best described as:", opts: ["Flow of electrons", "Opposition to current", "Electrical pressure", "Power consumption"], ans: 2 },
  { q: "The unit of current is:", opts: ["Volt", "Ampere", "Ohm", "Watt"], ans: 1 },
  { q: "Resistance is defined as:", opts: ["Flow of electrons", "Electrical pressure", "Opposition to current flow", "Energy storage"], ans: 2 },
  { q: "The unit of resistance is:", opts: ["Volt", "Ampere", "Ohm", "Joule"], ans: 2 },
  { q: "Ohm’s Law states that:", opts: ["V = I / R", "I = V × R", "I = V / R", "R = I / V"], ans: 2 },
  { q: "If resistance is constant, increasing voltage will:", opts: ["Decrease current", "Increase current", "Stop current", "Reverse current"], ans: 1 },
  { q: "If voltage is constant, increasing resistance will:", opts: ["Increase current", "Decrease current", "Not affect current", "Double current"], ans: 1 },
  { q: "A switch is used to:", opts: ["Increase voltage", "Store current", "Open or close a circuit", "Measure resistance"], ans: 2 },
  { q: "A fuse is used for:", opts: ["Amplification", "Protection", "Measurement", "Storage"], ans: 1 },
  { q: "When a circuit is closed:", opts: ["No current flows", "Current flows", "Voltage is zero", "Resistance is zero"], ans: 1 },
  { q: "When a circuit is open:", opts: ["Current flows freely", "No current flows", "Voltage increases", "Resistance disappears"], ans: 1 },
  { q: "Direct current (DC) flows in:", opts: ["Both directions", "One direction only", "Random directions", "Circular path"], ans: 1 },
  { q: "Alternating current (AC) flows in:", opts: ["One direction", "Two directions", "No direction", "Straight line"], ans: 1 },
  { q: "Which of the following is a DC source?", opts: ["Generator", "Socket outlet", "Battery", "Transformer"], ans: 2 },
  { q: "Which of the following is an AC source?", opts: ["Battery", "Photocell", "Socket outlet", "Cell"], ans: 2 },
  { q: "Heat in a conductor is mainly due to:", opts: ["Voltage", "Resistance", "Current", "Power"], ans: 1 },
  { q: "Resistance is caused by:", opts: ["Voltage drop", "Electron collisions", "Current increase", "Power supply"], ans: 1 },
  { q: "A short circuit results in:", opts: ["Low current", "High current", "No current", "Low voltage"], ans: 1 },
  { q: "A series circuit has:", opts: ["Multiple paths", "One path", "No path", "Infinite paths"], ans: 1 },
  { q: "A parallel circuit has:", opts: ["One path", "Multiple paths", "No connection", "Single loop only"], ans: 1 },
  { q: "A circuit must have a ______ for current to flow.", opts: ["CPU", "Closed path", "Open switch", "Resistor only"], ans: 1 },
  { q: "The flow of electrons is called:", opts: ["Voltage", "Resistance", "Current", "Power"], ans: 2 },
  { q: "The SI unit of voltage is:", opts: ["Ampere", "Ohm", "Volt", "Joule"], ans: 2 },
  { q: "The SI unit of current is:", opts: ["Volt", "Ampere", "Watt", "Ohm"], ans: 1 },
  { q: "The SI unit of resistance is:", opts: ["Volt", "Ampere", "Ohm", "Watt"], ans: 2 },
  { q: "Which device connects and disconnects a circuit?", opts: ["Fuse", "Switch", "Battery", "Resistor"], ans: 1 },
  { q: "A fuse operates when:", opts: ["Voltage drops", "Current exceeds limit", "Resistance decreases", "Power stops"], ans: 1 },
  { q: "Example of load includes:", opts: ["Battery", "Lamp", "Wire", "Switch"], ans: 1 },
  { q: "The purpose of wires in a circuit is to:", opts: ["Store energy", "Provide path", "Increase voltage", "Reduce current"], ans: 1 },
  { q: "Voltage is analogous to:", opts: ["Water flow", "Water pressure", "Pipe size", "Tank volume"], ans: 1 },
  { q: "Current is analogous to:", opts: ["Pressure", "Flow of water", "Pipe resistance", "Tank height"], ans: 1 },
  { q: "Resistance is analogous to:", opts: ["Pipe width", "Flow rate", "Obstruction in pipe", "Pump"], ans: 2 },
  { q: "The relationship V = IR represents:", opts: ["Kirchhoff’s law", "Ohm’s law", "Faraday’s law", "Newton’s law"], ans: 1 },
  { q: "Increasing resistance will:", opts: ["Increase current", "Reduce current", "Stop voltage", "Increase voltage"], ans: 1 },
  { q: "Current is directly proportional to:", opts: ["Resistance", "Voltage", "Power", "Heat"], ans: 1 },
  { q: "Current is inversely proportional to:", opts: ["Voltage", "Resistance", "Power", "Energy"], ans: 1 },
  { q: "An open circuit means:", opts: ["Complete path", "Broken path", "No resistance", "High voltage"], ans: 1 },
  { q: "A closed circuit means:", opts: ["Broken path", "Complete path", "No current", "Infinite resistance"], ans: 1 },
  { q: "Electrical energy is supplied by:", opts: ["Load", "Source", "Wire", "Switch"], ans: 1 },
  { q: "Without a load, a circuit cannot:", opts: ["Conduct", "Perform work", "Carry voltage", "Carry current"], ans: 1 },
  { q: "AC waveform is:", opts: ["Straight line", "Constant", "Alternating wave", "Zero line"], ans: 2 },
  { q: "DC waveform is:", opts: ["Alternating", "Constant", "Fluctuating", "Random"], ans: 1 },
  { q: "A circuit with excessive current is dangerous because:", opts: ["Low voltage", "Heat generation", "No resistance", "Low power"], ans: 1 },
  { q: "Fuse protects against:", opts: ["Voltage drop", "Overcurrent", "Low resistance", "Low voltage"], ans: 1 },
  { q: "Current flows only when circuit is:", opts: ["Open", "Closed", "Shorted", "Broken"], ans: 1 },
  { q: "The flow of electrons requires:", opts: ["Open path", "Closed loop", "Broken wire", "No source"], ans: 1 },
  { q: "Electricity cannot flow without:", opts: ["CPU", "Power source", "Monitor", "Keyboard"], ans: 1 },
  { q: "A diode is best described as a:", opts: ["Three-terminal device", "One-terminal device", "Two-terminal semiconductor device", "Multi-terminal circuit"], ans: 2 },
  { q: "A diode primarily allows current to flow in:", opts: ["Both directions", "One direction only", "No direction", "Circular direction"], ans: 1 },
  { q: "Another name for a diode is:", opts: ["Amplifier", "Rectifier", "Oscillator", "Transformer"], ans: 1 },
  { q: "A diode converts AC into:", opts: ["AC", "Pure DC", "Pulsating DC", "High voltage"], ans: 2 },
  { q: "The two terminals of a diode are:", opts: ["Base and collector", "Input and output", "Anode and cathode", "Positive and neutral"], ans: 2 },
  { q: "The anode of a diode is:", opts: ["Negative terminal", "Positive terminal", "Neutral terminal", "Ground terminal"], ans: 1 },
  { q: "The cathode of a diode is:", opts: ["Positive terminal", "Negative terminal", "Neutral terminal", "Input terminal"], ans: 1 },
  { q: "Forward bias occurs when:", opts: ["Positive voltage is applied to cathode", "Positive voltage is applied to anode", "No voltage is applied", "AC voltage is applied"], ans: 1 },
  { q: "In forward bias, the diode:", opts: ["Blocks current", "Conducts current", "Stores charge", "Amplifies signal"], ans: 1 },
  { q: "Reverse bias occurs when:", opts: ["Positive is applied to anode", "Positive is applied to cathode", "No voltage is applied", "Equal voltage is applied"], ans: 1 },
  { q: "In reverse bias, a diode acts as:", opts: ["Conductor", "Insulator", "Amplifier", "Capitor"], ans: 1 },
  { q: "The ‘ON’ state of a diode occurs during:", opts: ["Reverse bias", "Forward bias", "No bias", "AC bias"], ans: 1 },
  { q: "The ‘OFF’ state of a diode occurs during:", opts: ["Forward bias", "Reverse bias", "High voltage", "Low resistance"], ans: 1 },
  { q: "The minimum voltage required for a diode to conduct is called:", opts: ["Breakdown voltage", "Peak voltage", "Cut-in voltage", "Threshold current"], ans: 2 },
  { q: "Breakdown voltage occurs when:", opts: ["Forward voltage is high", "Reverse voltage exceeds limit", "Current is zero", "Resistance is zero"], ans: 1 },
  { q: "During forward bias, a diode has:", opts: ["Infinite resistance", "High resistance", "Low resistance", "Zero resistance"], ans: 2 },
  { q: "During reverse bias, a diode has:", opts: ["Low resistance", "Zero resistance", "High resistance", "No resistance"], ans: 2 },
  { q: "Most diodes are made from:", opts: ["Copper", "Silicon or germanium", "Iron", "Aluminum"], ans: 1 },
  { q: "Semiconductor materials are preferred because:", opts: ["They are heavy", "They conduct perfectly", "Their conductivity can be controlled", "They are magnetic"], ans: 2 },
  { q: "A diode behaves like:", opts: ["Two-way switch", "One-way switch", "Amplifier", "Battery"], ans: 1 },
  { q: "Biasing refers to:", opts: ["Removing voltage", "Applying voltage to a diode", "Increasing resistance", "Measuring current"], ans: 1 },
  { q: "When no voltage is applied, the diode is:", opts: ["ON", "OFF", "Shorted", "Amplifying"], ans: 1 },
  { q: "The direction of current in forward bias is:", opts: ["Opposite arrow", "Same as arrow", "Random", "Circular"], ans: 1 },
  { q: "Reverse current flows when:", opts: ["Forward bias", "Reverse bias beyond breakdown", "No voltage", "AC supply"], ans: 1 },
  { q: "A diode array consists of:", opts: ["One diode", "Two diodes", "Multiple diodes", "No diode"], ans: 2 },
  { q: "A diode array is usually fabricated on:", opts: ["Plastic", "Glass", "Silicon chip", "Wood"], ans: 2 },
  { q: "Typical diode arrays contain:", opts: ["2 diodes", "4 or more diodes", "Only 1 diode", "Unlimited diodes"], ans: 1 },
  { q: "Diode arrays improve:", opts: ["Weight", "Reliability", "Voltage", "Resistance"], ans: 1 },
  { q: "Diode arrays reduce:", opts: ["Current", "Assembly time", "Voltage", "Power"], ans: 1 },
  { q: "Diode arrays are used in:", opts: ["Cooking", "Computer I/O ports", "Mechanical systems", "Plumbing"], ans: 1 },
  { q: "Diode arrays are useful in:", opts: ["LAN/WAN networks", "Engines", "Motors", "Batteries"], ans: 0 },
  { q: "A photodiode detects:", opts: ["Heat", "Light", "Sound", "Pressure"], ans: 1 },
  { q: "A diode array detector measures:", opts: ["Voltage", "Current", "Light intensity", "Resistance"], ans: 2 },
  { q: "Diode array detectors are used in:", opts: ["Farming", "Chromatography", "Cooking", "Welding"], ans: 1 },
  { q: "PDA stands for:", opts: ["Power Device Amplifier", "Photo Diode Array", "Pulse Data Analyzer", "Parallel Device Array"], ans: 1 },
  { q: "PDA detectors measure:", opts: ["Current", "Voltage", "Absorbance", "Resistance"], ans: 2 },
  { q: "Diode array detectors allow measurement of:", opts: ["Single wavelength only", "Multiple wavelengths", "No wavelength", "Voltage only"], ans: 1 },
  { q: "One advantage of diode arrays is:", opts: ["High cost", "Low reliability", "Faster analysis", "Large size"], ans: 2 },
  { q: "Electronic circuits are used to:", opts: ["Block current", "Control and direct current", "Store water", "Produce heat only"], ans: 1 },
  { q: "An electronic circuit consists of:", opts: ["Only wires", "Components and connections", "Only resistors", "Only capacitors"], ans: 1 },
  { q: "Examples of circuit components include:", opts: ["CPU only", "Resistors, capacitors, transistors", "Monitor", "Keyboard"], ans: 1 },
  { q: "A resistor is used to:", opts: ["Store energy", "Oppose current", "Amplify signal", "Generate voltage"], ans: 1 },
  { q: "A capacitor is used to:", opts: ["Oppose current", "Store charge", "Amplify signal", "Generate heat"], ans: 1 },
  { q: "A transistor can act as:", opts: ["Load", "Switch and amplifier", "Battery", "Wire"], ans: 1 },
  { q: "Conductive paths in circuits are made of:", opts: ["Wood", "Plastic", "Wires or traces", "Rubber"], ans: 2 },
  { q: "Without a power source, a circuit:", opts: ["Works normally", "Cannot function", "Increases voltage", "Stores energy"], ans: 1 },
  { q: "Without a load, a circuit:", opts: ["Cannot perform useful work", "Works faster", "Produces voltage", "Stores current"], ans: 0 },
  { q: "A switch in an electronic circuit is used to:", opts: ["Increase voltage", "Break or connect current", "Store energy", "Reduce resistance"], ans: 1 },
  { q: "Electronic switches are used in:", opts: ["Mechanical systems", "Logical operations", "Cooking devices", "Engines"], ans: 1 },
  { q: "Types of electrical circuits include:", opts: ["Only open and closed", "Open, closed, short, series, parallel", "Only parallel", "Only series"], ans: 1 },
  { q: "An integrated circuit (IC) is:", opts: ["A single resistor", "A complete electronic circuit in one package", "A power supply", "A switch"], ans: 1 },
  { q: "Another name for an integrated circuit is:", opts: ["Board", "Chip", "Wire", "Cell"], ans: 1 },
  { q: "ICs are fabricated on:", opts: ["Plastic", "Silicon", "Glass", "Copper"], ans: 1 },
  { q: "ICs contain:", opts: ["Only resistors", "Only capacitors", "Active and passive components", "Only transistors"], ans: 2 },
  { q: "Which of the following is an active component?", opts: ["Resistor", "Capacitor", "Transistor", "Wire"], ans: 2 },
  { q: "Which of the following is a passive component?", opts: ["Transistor", "Diode", "Resistor", "Amplifier"], ans: 2 },
  { q: "A transistor functions as:", opts: ["Load", "Switch and amplifier", "Battery", "Fuse"], ans: 1 },
  { q: "A capacitor stores:", opts: ["Voltage", "Current", "Electric charge", "Resistance"], ans: 2 },
  { q: "A diode allows current:", opts: ["In both directions", "In one direction", "In no direction", "Randomly"], ans: 1 },
  { q: "Discrete circuits are:", opts: ["Very small", "Fabricated on one chip", "Made from separate components", "Always digital"], ans: 2 },
  { q: "Integrated circuits are:", opts: ["Large and heavy", "Small and compact", "Expensive", "High power only"], ans: 1 },
  { q: "Compared to discrete circuits, ICs are:", opts: ["Bigger", "More expensive", "Smaller and cheaper", "Less reliable"], ans: 2 },
  { q: "One advantage of ICs is:", opts: ["High power consumption", "Large size", "Increased reliability", "High weight"], ans: 2 },
  { q: "ICs require:", opts: ["High power", "Low power", "No power", "Infinite power"], ans: 1 },
  { q: "One disadvantage of ICs is:", opts: ["High cost", "Large size", "Cannot handle high power", "Low speed"], ans: 2 },
  { q: "If one component in an IC fails:", opts: ["Only that part is replaced", "Entire IC is replaced", "Nothing happens", "Circuit improves"], ans: 1 },
  { q: "SSI stands for:", opts: ["Small Scale Integration", "Simple System Integration", "Signal System Integration", "Super Scale Integration"], ans: 0 },
  { q: "SSI typically contains:", opts: ["Millions of transistors", "Few components", "No components", "Only capacitors"], ans: 1 },
  { q: "MSI stands for:", opts: ["Medium Scale Integration", "Maximum System Integration", "Micro System Integration", "Multi Scale Integration"], ans: 0 },
  { q: "MSI typically contains:", opts: ["10–100 components", "1–5 components", "Millions of components", "No components"], ans: 0 },
  { q: "LSI stands for:", opts: ["Large Scale Integration", "Low Scale Integration", "Linear System Integration", "Logical Scale Integration"], ans: 0 },
  { q: "LSI contains:", opts: ["Few components", "Hundreds to thousands", "Millions only", "No transistors"], ans: 1 },
  { q: "VLSI stands for:", opts: ["Very Large Scale Integration", "Variable Large System Integration", "Voltage Level System Integration", "Visual Logic System Integration"], ans: 0 },
  { q: "VLSI contains:", opts: ["Few components", "Thousands to millions", "Only one component", "No components"], ans: 1 },
  { q: "ULSI stands for:", opts: ["Ultra Large Scale Integration", "Universal Logic System Integration", "Unit Level System Integration", "Ultra Logic System Integration"], ans: 0 },
  { q: "ULSI contains:", opts: ["Few components", "Millions to billions", "Only one transistor", "No transistors"], ans: 1 },
  { q: "GSI refers to:", opts: ["Giant Scale Integration", "General System Integration", "Global System Integration", "Ground System Integration"], ans: 0 },
  { q: "GSI is currently:", opts: ["Common", "Obsolete", "In research stage", "Fully developed"], ans: 2 },
  { q: "Wafer preparation involves:", opts: ["Heating", "Cleaning silicon surface", "Etching", "Doping"], ans: 1 },
  { q: "Silicon wafers are used because:", opts: ["They are cheap", "They are semiconductors", "They are strong", "They are magnetic"], ans: 1 },
  { q: "Oxidation forms:", opts: ["Silicon", "Silicon dioxide", "Metal layer", "Gas layer"], ans: 1 },
  { q: "Photolithography uses:", opts: ["Heat", "Light", "Sound", "Pressure"], ans: 1 },
  { q: "Photoresist is:", opts: ["Metal", "Light-sensitive material", "Insulator", "Conductor"], ans: 1 },
  { q: "Etching is used to:", opts: ["Add material", "Remove unwanted material", "Increase voltage", "Store energy"], ans: 1 },
  { q: "Doping is the process of:", opts: ["Cleaning wafer", "Adding impurities", "Removing metal", "Heating silicon"], ans: 1 },
  { q: "Boron doping creates:", opts: ["n-type", "p-type", "neutral type", "metal type"], ans: 1 },
  { q: "Phosphorus doping creates:", opts: ["p-type", "n-type", "neutral", "oxide"], ans: 1 },
  { q: "Deposition involves:", opts: ["Removing layers", "Adding layers", "Breaking circuits", "Testing circuits"], ans: 1 },
  { q: "Metallization is used for:", opts: ["Cleaning", "Interconnections", "Doping", "Etching"], ans: 1 },
  { q: "Vias are used to:", opts: ["Remove layers", "Connect layers", "Store charge", "Increase resistance"], ans: 1 },
  { q: "CMP stands for:", opts: ["Chemical Mechanical Planarization", "Circuit Measurement Process", "Current Measurement Protocol", "Chip Manufacturing Process"], ans: 0 },
  { q: "CMP is used to:", opts: ["Heat wafer", "Smooth surface", "Remove doping", "Add voltage"], ans: 1 },
  { q: "Testing ensures:", opts: ["Appearance", "Functionality", "Color", "Size"], ans: 1 },
  { q: "Dicing refers to:", opts: ["Cutting wafer into chips", "Heating wafer", "Cleaning wafer", "Testing wafer"], ans: 0 },
  { q: "Packaging is used to:", opts: ["Destroy chips", "Protect chips", "Heat chips", "Remove chips"], ans: 1 },
  { q: "Digital ICs operate on:", opts: ["Continuous signals", "Discrete levels", "Heat", "Light"], ans: 1 },
  { q: "Analog ICs operate on:", opts: ["Discrete signals", "Continuous signals", "Binary signals", "Digital signals"], ans: 1 },
  { q: "Mixed ICs combine:", opts: ["Analog only", "Digital only", "Analog and digital", "Mechanical systems"], ans: 2 },
  { q: "An example of mixed IC application is:", opts: ["Switch", "A/D converter", "Wire", "Battery"], ans: 1 },
  { q: "Integrated circuits are important because they:", opts: ["Increase size", "Reduce efficiency", "Enable modern electronics", "Reduce speed"], ans: 2 }
];