const gst112Questions = [
  { q: "Culture is best defined as", opts: ["Natural environment", "Biological inheritance", "Way of life of a people", "Government system"], ans: 2 },
  { q: "Culture is transmitted through", opts: ["Genetics", "Symbols", "Instinct", "Reflex"], ans: 1 },
  { q: "The word “culture” is derived from", opts: ["Greek", "Latin", "French", "Arabic"], ans: 1 },
  { q: "Culture includes", opts: ["Only material things", "Only beliefs", "Both material and non-material elements", "Only traditions"], ans: 2 },
  { q: "Which is NOT material culture?", opts: ["Clothes", "Language", "Tools", "Vehicles"], ans: 1 },
  { q: "Culture is", opts: ["Inherited biologically", "Learned behavior", "Fixed", "Individual"], ans: 1 },
  { q: "Culture promotes", opts: ["Division", "Unity", "Isolation", "Conflict"], ans: 1 },
  { q: "Culture is transmitted", opts: ["Horizontally only", "Vertically only", "Both vertically and horizontally", "Not transmitted"], ans: 2 },
  { q: "Which scholar defined culture as learned behavior?", opts: ["Taylor", "Linton", "Marx", "Weber"], ans: 1 },
  { q: "Culture is", opts: ["Static", "Dynamic", "Permanent", "Unchangeable"], ans: 1 },
  { q: "Culture varies from", opts: ["Person to person only", "Place to place", "Time only", "Family only"], ans: 1 },
  { q: "Culture is", opts: ["Individual", "Social", "Biological", "Natural"], ans: 1 },
  { q: "Non-material culture includes", opts: ["Cars", "Books", "Beliefs", "Clothes"], ans: 2 },
  { q: "Culture is", opts: ["Instinctive", "Acquired", "Genetic", "Automatic"], ans: 1 },
  { q: "Culture helps in", opts: ["Conflict creation", "Problem solving", "Ignorance", "Isolation"], ans: 1 },
  { q: "Culture is shared by", opts: ["Individuals", "Groups", "Animals", "Machines"], ans: 1 },
  { q: "Culture is", opts: ["Natural", "Man-made", "Divine", "Accidental"], ans: 1 },
  { q: "Which is a characteristic of culture?", opts: ["Static", "Dynamic", "Genetic", "Fixed"], ans: 1 },
  { q: "Culture provides", opts: ["Behavior patterns", "Biological traits", "Instincts", "Reflexes"], ans: 0 },
  { q: "Culture is", opts: ["Private", "Public", "Secret", "Hidden"], ans: 1 },
  { q: "Marriage is a", opts: ["Political system", "Social institution", "Religious law", "Economic tool"], ans: 1 },
  { q: "Marriage regulates", opts: ["Trade", "Religion", "Reproduction", "Education"], ans: 2 },
  { q: "Marriage provides", opts: ["Legitimacy to children", "Wealth", "Fame", "Education"], ans: 0 },
  { q: "Monogamy means", opts: ["One man many wives", "One woman many men", "One man one woman", "Group marriage"], ans: 2 },
  { q: "Polygyny means", opts: ["One woman many men", "One man many women", "Group marriage", "Serial marriage"], ans: 1 },
  { q: "Polyandry means", opts: ["One man many women", "One woman many men", "One couple", "Group"], ans: 1 },
  { q: "Marriage creates", opts: ["School", "Family", "Government", "Religion"], ans: 1 },
  { q: "Economic function of marriage is", opts: ["Reproduction", "Cooperation", "Worship", "Education"], ans: 1 },
  { q: "Social function of marriage is", opts: ["Family formation", "Trade", "Education", "Religion"], ans: 0 },
  { q: "Biological function of marriage is", opts: ["Wealth", "Children", "Power", "Status"], ans: 1 },
  { q: "Bride price is common in", opts: ["Western culture", "African culture", "Asian culture", "European culture"], ans: 1 },
  { q: "Igbo marriage involves", opts: ["Individual decision", "Family participation", "Government approval", "Church only"], ans: 1 },
  { q: "Yoruba marriage has", opts: ["3 stages", "5 stages", "7 stages", "10 stages"], ans: 2 },
  { q: "Hausa marriage includes", opts: ["Na gani ina so", "Igba nkwu", "Ifojusode", "Idana"], ans: 0 },
  { q: "Marriage in Igala culture is", opts: ["Optional", "Mandatory for children legitimacy", "Illegal", "Temporary"], ans: 1 },
  { q: "Family is", opts: ["Largest unit", "Smallest social unit", "Political unit", "Religious unit"], ans: 1 },
  { q: "Nuclear family consists of", opts: ["Parents and children", "Extended relatives", "Community", "Tribe"], ans: 0 },
  { q: "Extended family includes", opts: ["Only parents", "Relatives", "Friends", "Neighbors"], ans: 1 },
  { q: "Family function includes", opts: ["Reproduction", "Isolation", "Conflict", "War"], ans: 0 },
  { q: "Citizenship means", opts: ["Being human", "Belonging to a country", "Living abroad", "Working"], ans: 1 },
  { q: "Citizenship by birth is acquired", opts: ["Through marriage", "At birth", "By law", "By vote"], ans: 1 },
  { q: "Citizenship by registration requires", opts: ["Wealth", "Good character", "Fame", "Education"], ans: 1 },
  { q: "Citizenship by naturalization requires", opts: ["Travel", "Residence", "Marriage", "Birth"], ans: 1 },
  { q: "Human rights are", opts: ["Optional", "Universal", "Limited", "Conditional"], ans: 1 },
  { q: "Human rights are", opts: ["Transferable", "Inalienable", "Sellable", "Optional"], ans: 1 },
  { q: "Human rights apply to", opts: ["Citizens only", "Everyone", "Leaders", "Adults"], ans: 1 },
  { q: "Human dignity refers to", opts: ["Wealth", "Worth of individuals", "Status", "Power"], ans: 1 },
  { q: "Rights are protected by", opts: ["Family", "Law", "Religion", "Friends"], ans: 1 },
  { q: "Non-discrimination means", opts: ["Equality", "Bias", "Segregation", "Preference"], ans: 0 },
  { q: "Human rights include", opts: ["Education", "Slavery", "War", "Oppression"], ans: 0 },
  { q: "Citizenship education promotes", opts: ["Ignorance", "Awareness", "Corruption", "Isolation"], ans: 1 },
  { q: "Democracy requires", opts: ["Dictatorship", "Participation", "Silence", "Force"], ans: 1 },
  { q: "Constitution defines", opts: ["Culture", "Rights", "Language", "Food"], ans: 1 },
  { q: "Dual citizenship means", opts: ["One country", "Two countries", "No country", "Three countries"], ans: 1 },
  { q: "Renunciation means", opts: ["Acceptance", "Giving up citizenship", "Registration", "Birth"], ans: 1 }
];
