const cosQuestions = [
            { q: "What is a computer?", opts: ["An electronic device that processes data", "A mechanical typewriter", "A power supply unit", "A type of calculator"], ans: 0 },
            { q: "Which of the following is an input device?", opts: ["Printer", "Monitor", "Keyboard", "Speaker"], ans: 2 },
            { q: "The basic operations performed by a computer are:", opts: ["Arithmetic operations", "Logical operations", "Storage and retrieval", "All of the above"], ans: 3 },
            { q: "What does RAM stand for?", opts: ["Read Access Memory", "Random Access Memory", "Read Arithmetic Memory", "Random Arithmetic Memory"], ans: 1 },
            { q: "Which of these is a secondary memory?", opts: ["RAM", "Hard Disk", "CPU", "ROM"], ans: 1 },
            { q: "The full form of CPU is:", opts: ["Central Processing Unit", "Computer Processing Unit", "Central Programming Unit", "Computer Programming Unit"], ans: 0 },
            { q: "Which of these is an Operating System?", opts: ["MS Word", "Chrome", "Windows", "Fortnite"], ans: 2 },
            { q: "The smallest unit of data in a computer is?", opts: ["Byte", "Kilo", "Bit", "Mega"], ans: 2 },
            { q: "Which device is used to convert a digital signal to an analog signal (and vice versa) for communication?", opts: ["Modem", "Monitor", "Printer", "Scanner"], ans: 0 },
            { q: "What is the primary use of an OS (Operating System)?", opts: ["To play games", "To manage computer hardware and software resources", "To browse the internet", "To edit photos"], ans: 1 },
            { q: "Which of these is volatile memory?", opts: ["Hard Disk", "ROM", "RAM", "Flash Drive"], ans: 2 },
            { q: "The work of the ALU (Arithmetic Logic Unit) is:", opts: ["To store data", "To perform mathematical and logical calculations", "To control the flow of data", "To display graphics"], ans: 1 },
            { q: "Which generation of computer used vacuum tubes?", opts: ["First Generation", "Second Generation", "Third Generation", "Fourth Generation"], ans: 0 },
            { q: "What type of software is Microsoft PowerPoint?", opts: ["Database", "Operating System", "Presentation Software", "Spreadsheet"], ans: 2 },
            { q: "Which port is commonly used to connect a modern printer to the computer?", opts: ["VGA", "USB", "HDMI", "PS/2"], ans: 1 },
            { q: "What is a pixel?", opts: ["A type of virus", "The smallest controllable element of a picture represented on the screen", "A programming language", "A sound file"], ans: 1 },
            { q: "Which of these is NOT a web browser?", opts: ["Chrome", "Firefox", "Photoshop", "Edge"], ans: 2 },
            { q: "What does URL stand for?", opts: ["Uniform Resource Locator", "Universal Resource Locator", "Uniform Resource Link", "Unique Resource Link"], ans: 0 },
            { q: "Which of these is an example of malware?", opts: ["Firewall", "Virus", "Antivirus", "Firefox"], ans: 1 },
            { q: "What is a firewall?", opts: ["A wall that protects the computer from fire", "A network security system that monitors and controls incoming and outgoing traffic", "A type of virus", "A web browser"], ans: 1 },
            { q: "Which device is used for Uninterrupted Power Supply?", opts: ["USB", "UPS", "CPU", "GPS"], ans: 1 },
            { q: "What is a high-level programming language?", opts: ["Windows", "Python", "Linux", "Unix"], ans: 1 },
            { q: "The meaning of HTTP is:", opts: ["HyperText Transfer Protocol", "HyperText Transmission Protocol", "High Transfer Text Protocol", "HyperText Type Protocol"], ans: 0 },
            { q: "Which unit is used to measure the processing speed of the CPU?", opts: ["Gigabytes (GB)", "Hertz (Hz/GHz)", "Pixels", "Bits per second"], ans: 1 },
            { q: "What is a computer application?", opts: ["The physical parts of a computer", "Software designed to perform specific tasks for the user", "The operating system", "The internet"], ans: 1 },
            { q: "Which of these is NOT a type of printer?", opts: ["Laserjet", "Plotter", "Monitor", "Inkjet"], ans: 2 },
            { q: "What is the purpose of the monitor?", opts: ["To process data", "To input data", "To display visual output", "To store files"], ans: 2 },
            { q: "Which device is used to generate input graphics or copy documents into the computer?", opts: ["Scanner", "Printer", "Speaker", "Projector"], ans: 0 },
            { q: "What is the full form of PDF?", opts: ["Printed Document Format", "Portable Document Format", "Public Document File", "Personal Data File"], ans: 1 },
            { q: "Which of these refers to a computer network?", opts: ["CPU", "LAN (Local Area Network)", "USB", "PNG"], ans: 1 },
            { q: "What is the purpose of BIOS?", opts: ["To edit videos", "To initialize hardware during booting", "To browse the web", "To scan for viruses"], ans: 1 },
            { q: "Which device is used to point and select items on the screen?", opts: ["Keyboard", "Mouse", "Speaker", "Printer"], ans: 1 },
            { q: "Which of these is NOT a valid file extension?", opts: [".exe", ".doc", ".txt", ".cpu"], ans: 3 },
            { q: "What is the function of the motherboard?", opts: ["To supply power", "To hold and connect the crucial electronic components of the computer", "To display images", "To type text"], ans: 1 },
            { q: "Which is a search engine?", opts: ["Google", "Microsoft Word", "Windows", "Photoshop"], ans: 0 },
            { q: "The purpose of a server is?", opts: ["To type documents", "To provide resources, data, or services to other computers on a network", "To play music", "To cool down the CPU"], ans: 1 },
            { q: "A device that enables online video chat is a?", opts: ["Webcam", "Scanner", "Printer", "Joystick"], ans: 0 },
            { q: "The function of an IP address is?", opts: ["To identify the user's name", "To identify a device on a network", "To measure internet speed", "To protect against viruses"], ans: 1 },
            { q: "The purpose of a compiler is?", opts: ["To write code", "To translate high-level code into machine code", "To execute games", "To browse the internet"], ans: 1 },
            { q: "The function of ROM (Read Only Memory) is?", opts: ["To store temporary data", "To store permanent instructions required to start the computer", "To store user files", "To increase game speed"], ans: 1 },
            { q: "What generation of computer uses an Integrated Circuit (IC)?", opts: ["First", "Second", "Third", "Fourth"], ans: 2 },
            { q: "What is Cloud Computing?", opts: ["Computing during a storm", "Delivering computing services (servers, storage, etc.) over the internet", "Using a wireless mouse", "Printing from a cloud printer"], ans: 1 },
            { q: "Which of these is a type of malware?", opts: ["Trojan", "Anti-virus", "Firewall", "Backup"], ans: 0 },
            { q: "What is the purpose of a device driver?", opts: ["To physically drive the computer", "A program that operates or controls a particular type of device attached to a computer", "To cool the system", "To supply power"], ans: 1 },
            { q: "Which is NOT a type of computer?", opts: ["Supercomputer", "Mainframe", "Microcomputer", "Internet"], ans: 3 },
            { q: "What is a database?", opts: ["A base for data entry", "An organized collection of structured information, or data", "A type of monitor", "A programming language"], ans: 1 },
            { q: "Which is NOT a type of computer memory?", opts: ["RAM", "ROM", "Monitor", "Cache"], ans: 2 },
            { q: "What is the function of an Ethernet card (NIC)?", opts: ["To display graphics", "To connect a computer to a network", "To store files", "To print documents"], ans: 1 },
            { q: "What is the purpose of a PSU (Power Supply Unit)?", opts: ["To store data", "To convert mains AC to low-voltage regulated DC power for the internal components", "To process calculations", "To cool the CPU"], ans: 1 },
            { q: "A device used to control video games is a?", opts: ["Joystick / Gamepad", "Scanner", "Printer", "Microphone"], ans: 0 },
            { q: "A network switch is used to?", opts: ["Turn the internet on and off", "Connect multiple devices on a computer network and route data to the destination", "Scan for viruses", "Print photos"], ans: 1 },
            { q: "What is the purpose of virtual memory?", opts: ["To download more RAM", "To use a section of the hard drive as an extension of RAM", "To play virtual reality games", "To store emails"], ans: 1 },
            { q: "What device is typically used to connect a home network to the Internet Service Provider (ISP)?", opts: ["Monitor", "Modem", "Printer", "Sound Card"], ans: 1 },
            { q: "A sound card is used to?", opts: ["Record video", "Process and deliver audio output", "Connect to the internet", "Save Word documents"], ans: 1 },
            { q: "Which is NOT a type of monitor technology?", opts: ["LED", "CRT", "LCD", "UPS"], ans: 3 },
            { q: "The use of a backup is to?", opts: ["Go back to a previous webpage", "Create a copy of data to recover it in case of data loss", "Speed up the computer", "Hack a system"], ans: 1 },
            { q: "Which is a type of computer file system?", opts: ["NTFS", "HTTP", "HTML", "URL"], ans: 0 },
            { q: "What is the purpose of the taskbar in Windows?", opts: ["To physically hold the monitor", "To locate and launch programs, and view currently open windows", "To clean the screen", "To cool the keyboard"], ans: 1 },
            { q: "What is the purpose of the heat sink?", opts: ["To heat up the computer", "To dissipate heat from the CPU or other components to prevent overheating", "To store hot files", "To burn CDs"], ans: 1 },
            { q: "Which is NOT a type of user interface?", opts: ["GUI (Graphical User Interface)", "CLI (Command Line Interface)", "Apps", "VUI (Voice User Interface)"], ans: 2 },
            { q: "What is the purpose of the Registry in Windows?", opts: ["To register users online", "A central database used to store configuration information and settings", "To write emails", "To clean dust"], ans: 1 },
            { q: "A device used for short-range wireless connection is?", opts: ["Bluetooth", "Ethernet", "Fiber Optic", "Satellite"], ans: 0 },
            { q: "What is the function of the CPU fan?", opts: ["To make noise", "To actively cool the heat sink and CPU", "To spin the hard drive", "To power the monitor"], ans: 1 },
            { q: "Which is NOT a type of computer case form factor?", opts: ["Tower", "Laptop", "Server"], ans: 2 },
            { q: "Which device is NOT a type of Input/Output (I/O) device?", opts: ["Mouse", "Touchscreen", "CPU", "Modem"], ans: 2 },
            { q: "Which is a type of computer battery used on the motherboard?", opts: ["CMOS Battery", "RAM Battery", "AA Battery", "Car Battery"], ans: 0 },
            { q: "A device used for network protection from external threats is?", opts: ["Firewall", "Switch", "Hub", "Repeater"], ans: 0 },
            { q: "The function of a RAID system is to?", opts: ["Kill computer bugs", "Combine multiple disk drive components into a logical unit for redundancy or performance", "Connect to WiFi", "Play videos"], ans: 1 },
            { q: "Which is NOT a type of computer display connection?", opts: ["HDMI", "VGA", "DisplayPort", "RAM"], ans: 3 },
            { q: "The purpose of System Restore is to?", opts: ["Clean the monitor", "Revert the computer's state to a previous point in time", "Delete all files", "Charge the battery"], ans: 1 },
            { q: "Which is NOT a type of physical keyboard mechanism?", opts: ["Mechanical", "Membrane", "Digital (Virtual)", "Scissor-switch"], ans: 2 },
            { q: "What is the purpose of Disk Defragmentation?", opts: ["To delete viruses", "To organize files on the disk to improve access speed", "To break the disk", "To install Windows"], ans: 1 },
            { q: "What is a computer program?", opts: ["A TV show about computers", "A set of instructions that a computer can execute", "A hardware component", "A user manual"], ans: 1 },
            { q: "A program used for software development (coding) is called?", opts: ["IDE (Integrated Development Environment)", "Media Player", "Calculator", "Browser"], ans: 0 },
            { q: "An example of an interpreted language is?", opts: ["C++", "Python", "Assembly", "Machine Code"], ans: 1 },
            { q: "What is Firmware?", opts: ["Soft pillows", "Permanent software programmed into a read-only memory", "A heavy monitor", "An antivirus"], ans: 1 },
            { q: "The purpose of an algorithm is to?", opts: ["Confuse the user", "Provide a step-by-step procedure to solve a problem", "Heat the CPU", "Play music"], ans: 1 },
            { q: "An example of Cloud Storage is?", opts: ["Google Drive / Dropbox", "USB Stick", "CD-ROM", "Floppy Disk"], ans: 0 },
            { q: "Accumulation of dust in the cooling fan causes?", opts: ["Faster processing", "Overheating", "Better graphics", "More storage"], ans: 1 },
            { q: "What is the full form of HTML?", opts: ["HyperText Markup Language", "HighText Machine Language", "HyperText Marking Link", "High Transfer Main Language"], ans: 0 },
            { q: "What is an algorithm?", opts: ["A hardware part", "A specific set of instructions for carrying out a procedure", "A type of monitor", "An input device"], ans: 1 },
            { q: "What is the difference between a compiler and an interpreter?", opts: ["Compiler runs line by line; Interpreter translates the whole code at once", "Compiler translates the whole code at once; Interpreter runs line by line", "Both do the exact same thing", "Compiler is hardware, Interpreter is software"], ans: 1 },
            { q: "What is the main function of the Arithmetic Logic Unit (ALU)?", opts: ["To connect to the internet", "To perform arithmetic and logic operations", "To store the OS", "To boot the computer"], ans: 1 },
            { q: "What is a bus in a computer system?", opts: ["A vehicle for transport", "A communication system that transfers data between components", "A type of power cable", "A cooling fan"], ans: 1 },
            { q: "Which layer of the OSI Model is responsible for logical addressing (IP addresses)?", opts: ["Physical Layer", "Network Layer", "Application Layer", "Session Layer"], ans: 1 },
            { q: "What is the purpose of caching?", opts: ["To delete old files", "To store frequently used data for quicker access", "To slow down the computer", "To encrypt data"], ans: 1 },
            { q: "What is data encapsulation?", opts: ["Deleting data", "The process of adding headers and trailers to data as it moves down the protocol stack", "Breaking the computer", "Compressing files"], ans: 1 },
            { q: "What is the primary difference between Open Source and Proprietary software?", opts: ["Open Source is free; Proprietary is always expensive", "Open Source source code is available to public; Proprietary is closed/owned by a company", "Open Source has viruses; Proprietary does not", "There is no difference"], ans: 1 },
            { q: "What is the standard keyboard shortcut to \"Copy\" selected text?", opts: ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Alt + F4"], ans: 1 },
            { q: "What is the standard keyboard shortcut to \"Paste\" text?", opts: ["Ctrl + P", "Ctrl + V", "Ctrl + C", "Ctrl + Z"], ans: 1 },
            { q: "Which component is often referred to as the \"brain\" of the computer?", opts: ["RAM", "CPU", "Hard Drive", "Motherboard"], ans: 1 },
            { q: "Who is known as the \"Father of the Computer\"?", opts: ["Bill Gates", "Charles Babbage", "Steve Jobs", "Alan Turing"], ans: 1 },
            { q: "What does \"SSD\" stand for in storage technology?", opts: ["Solid State Drive", "Super Speed Disk", "System Storage Device", "Serial State Disk"], ans: 0 },
            { q: "Which of these is a social media platform?", opts: ["LinkedIn", "Excel", "Linux", "Apache"], ans: 0 },
            { q: "What does \"WWW\" stand for in a website address?", opts: ["World Web Wide", "World Wide Web", "World Wide Wares", "Wide World Web"], ans: 1 },
            { q: "Which key is used to refresh the active window in most browsers?", opts: ["F1", "F5", "F10", "Esc"], ans: 1 },
            { q: "1 Kilobyte (KB) is equal to approximately:", opts: ["1000 Bytes (or 1024 Bytes)", "100 Bytes", "1000 Bits", "10 MegaBytes"], ans: 0 },
            { q: "What is \"Phishing\"?", opts: ["A game about fishing", "A cyber attack trying to trick users into revealing sensitive information", "Installing software", "Editing photos"], ans: 1 },
            { q: "Which of the following is an example of a Spreadsheet program?", opts: ["MS Word", "MS Excel", "Notepad", "VLC Player"], ans: 1 },
            { q: "What is the recycle bin used for?", opts: ["To store viruses", "To temporarily store deleted files", "To burn documents", "To keep important files safe"], ans: 1 }
        ];
