const cscQuestions = [
        { q: "A DBMS is a collection of ________.", opts: ["Programs only", "Interrelated data only", "Interrelated data and programs", "Files only"], ans: 2 },
        { q: "The primary goal of a DBMS is to provide ________.", opts: ["Fast computers", "Secure hardware", "Convenient and efficient data storage and retrieval", "Cheap storage"], ans: 2 },
        { q: "Information is transformed from data mainly through ________.", opts: ["Hardware", "DBMS", "Compiler", "Operating system"], ans: 1 },
        { q: "The word “data” comes from the word ________.", opts: ["Date", "Database", "Datum", "Detail"], ans: 2 },
        { q: "Data is considered ________.", opts: ["Meaningless", "Interchangeable", "Fixed", "Permanent"], ans: 1 },
        { q: "A database is an ________ collection of data.", opts: ["Random", "Unorganized", "Organized", "Temporary"], ans: 2 },
        { q: "Which of the following is NOT a database?", opts: ["MySQL", "Oracle", "MongoDB", "MS Word"], ans: 3 },
        { q: "File processing systems suffer from ________.", opts: ["Data independence", "Data redundancy", "High security", "Better performance"], ans: 1 },
        { q: "Data redundancy leads to ________.", opts: ["Data integrity", "Data inconsistency", "Data independence", "Data security"], ans: 1 },
        { q: "Difficulty in accessing data is a problem of ________.", opts: ["DBMS", "Database", "File system", "SQL"], ans: 2 },
        { q: "When data is scattered in different files, it is called ________.", opts: ["Data abstraction", "Data isolation", "Data integrity", "Metadata"], ans: 1 },
        { q: "Atomicity problems occur due to ________.", opts: ["User errors", "Incomplete transactions", "Hardware upgrades", "Backup systems"], ans: 1 },
        { q: "Concurrent-access anomalies occur when ________.", opts: ["One user accesses data", "Many users update data simultaneously", "Data is read-only", "Data is encrypted"], ans: 1 },
        { q: "Security is difficult to enforce in ________.", opts: ["DBMS", "Database", "File system", "SQL"], ans: 2 },
        { q: "Integrity constraints are enforced by ________.", opts: ["Users", "Programs", "Hardware", "Compiler"], ans: 1 },
        { q: "Data processed to be useful is called ________.", opts: ["Metadata", "Information", "Knowledge", "Database"], ans: 1 },
        { q: "Data that describes data is called ________.", opts: ["Information", "Metadata", "Schema", "Instance"], ans: 1 },
        { q: "A key is used to ________.", opts: ["Store data", "Encrypt data", "Uniquely identify records", "Delete data"], ans: 2 },
        { q: "A database system consists of ________.", opts: ["Hardware only", "Software only", "Data only", "Hardware, software, people, and data"], ans: 3 },
        { q: "DBMS software helps in ________.", opts: ["Playing media", "Data management", "Web browsing", "File compression"], ans: 1 },
        { q: "The self-describing nature of DBMS uses ________.", opts: ["SQL", "Tables", "Metadata", "Index"], ans: 2 },
        { q: "Program-data independence means ________.", opts: ["Programs depend on data", "Data depends on programs", "Programs and data are independent", "No programs are used"], ans: 2 },
        { q: "Data abstraction hides ________.", opts: ["User interfaces", "Storage details", "Data values", "Programs"], ans: 1 },
        { q: "Multiple views of data allow ________.", opts: ["One user view", "Same data for all users", "Different user perspectives", "No user access"], ans: 2 },
        { q: "Concurrency control ensures ________.", opts: ["Faster computers", "Correct transaction execution", "Data duplication", "More users"], ans: 1 },
        { q: "NTFS is an example of ________.", opts: ["DBMS", "File system", "Database", "Query language"], ans: 1 },
        { q: "SQL is used in ________.", opts: ["File systems", "DBMS", "Operating systems", "Hardware"], ans: 1 },
        { q: "DBMS provides ________ security than file system.", opts: ["Less", "Equal", "More", "No"], ans: 2 },
        { q: "Data consistency in DBMS is ________.", opts: ["Low", "Medium", "High", "Absent"], ans: 2 },
        { q: "Crash recovery is supported by ________.", opts: ["File system", "DBMS", "Compiler", "Editor"], ans: 1 },
        { q: "Airlines use DBMS mainly for ________.", opts: ["Music", "Ticket booking", "Gaming", "Chatting"], ans: 1 },
        { q: "DBMS is used in ________.", opts: ["Banking", "Education", "Healthcare", "All of the above"], ans: 3 },
        { q: "Facebook stores ________.", opts: ["Small data", "No data", "Large databases", "Temporary data"], ans: 2 },
        { q: "Wikipedia is an example of ________.", opts: ["Small database", "Very large database", "File system", "OS"], ans: 1 },
        { q: "E-commerce websites depend heavily on ________.", opts: ["Hardware", "DBMS", "Compiler", "Browser"], ans: 1 },
        { q: "Naive users ________.", opts: ["Write SQL", "Design databases", "Use applications without DBMS knowledge", "Maintain servers"], ans: 2 },
        { q: "Railway ticket users are ________.", opts: ["Sophisticated users", "Naive users", "Database designers", "DBAs"], ans: 1 },
        { q: "System analysts mainly ________.", opts: ["Write code", "Design hardware", "Analyze user requirements", "Backup databases"], ans: 2 },
        { q: "Sophisticated users interact with DBMS using ________.", opts: ["Hardware", "SQL queries", "File systems", "Backup tools"], ans: 1 },
        { q: "Database designers design ________.", opts: ["Queries only", "Tables and relationships", "Hardware", "Operating systems"], ans: 1 },
        { q: "DBA controls ________ levels of database.", opts: ["One", "Two", "Three", "Four"], ans: 2 },
        { q: "DBA provides ________.", opts: ["Security", "Backup", "Recovery", "All of the above"], ans: 3 },
        { q: "DBA account is also called ________.", opts: ["Guest account", "Normal user", "Superuser account", "Temporary account"], ans: 2 },
        { q: "Repairing database damage is the duty of ________.", opts: ["End user", "Programmer", "DBA", "Analyst"], ans: 2 },
        { q: "Creating user accounts is done by ________.", opts: ["Naive users", "DBA", "Designers", "Casual users"], ans: 1 },
        { q: "1-tier architecture has ________.", opts: ["Client only", "Server only", "Client, server, database on same machine", "Separate machines"], ans: 2 },
        { q: "1-tier architecture is mostly used for ________.", opts: ["Large web apps", "Learning purposes", "Banking", "Telecom"], ans: 1 },
        { q: "2-tier architecture follows ________.", opts: ["Peer-to-peer", "Client-server", "Centralized", "Distributed"], ans: 1 },
        { q: "ODBC and JDBC are used in ________.", opts: ["1-tier", "2-tier", "3-tier", "File system"], ans: 1 },
        { q: "3-tier architecture includes ________ layers.", opts: ["Two", "Three", "Four", "Five"], ans: 1 },
        { q: "The middle layer in 3-tier architecture is called ________.", opts: ["Client", "Database", "Application server", "Storage"], ans: 2 },
        { q: "3-tier architecture improves ________.", opts: ["Data loss", "Security", "Redundancy", "Inconsistency"], ans: 1 },
        { q: "Direct client-server interaction is avoided in ________.", opts: ["1-tier", "2-tier", "3-tier", "File system"], ans: 2 }
      ];
