const gns113Questions = [
    { q: "What is the primary function of a library?", opts: ["To sell books", "To store and provide access to information", "To print newspapers", "To repair computers"], ans: 1 },
    { q: "Which classification system is most commonly used in academic and university libraries?", opts: ["Dewey Decimal Classification", "Library of Congress Classification", "Alphabetical Classification", "ISBN System"], ans: 1 },
    { q: "What does ISBN stand for?", opts: ["International Standard Book Number", "Internal System Book Node", "International Standard Binding Number", "Inter-State Book Network"], ans: 0 },
    { q: "A list of books and other materials available in a library is called a:", opts: ["Dictionary", "Catalogue", "Encyclopedia", "Journal"], ans: 1 },
    { q: "Which of the following is considered a primary source of information?", opts: ["Textbook", "Original research diary", "Review article", "Encyclopedia entry"], ans: 1 },
    { q: "The section of the library where books cannot be borrowed to take home is called the:", opts: ["Circulation section", "Reference section", "Serials section", "Children's section"], ans: 1 },
    { q: "What is plagiarism?", opts: ["Reading books in the library", "Using someone else's work without proper acknowledgment", "Borrowing books for too long", "Writing an original essay"], ans: 1 },
    { q: "Which tool is used to find articles in journals, magazines, and newspapers?", opts: ["Dictionary", "Atlas", "Periodical Index / Database", "Thesaurus"], ans: 2 },
    { q: "OPAC stands for:", opts: ["Online Public Access Catalogue", "Offline Printed Article Collection", "Open Public Academic Center", "Online Periodical Access Code"], ans: 0 },
    { q: "A publication issued at regular intervals (like magazines or journals) is known as a:", opts: ["Monograph", "Serial / Periodical", "Manuscript", "Thesis"], ans: 1 },
    { q: "Which reference material would you use to find synonyms and antonyms?", opts: ["Encyclopedia", "Atlas", "Thesaurus", "Directory"], ans: 2 },
    { q: "The process of renewing borrowed library materials so you can keep them longer is called:", opts: ["Reservation", "Renewal", "Recall", "Registration"], ans: 1 },
    { q: "What is an abstract?", opts: ["The conclusion of a book", "A short summary of a research article or thesis", "The title page", "The bibliography"], ans: 1 },
    { q: "Which of these is NOT a Boolean operator used in library database searches?", opts: ["AND", "OR", "NOT", "BUT"], ans: 3 },
    { q: "What is a bibliography?", opts: ["A story of someone's life", "A list of sources used in a research paper", "A map of the library", "A library fine receipt"], ans: 1 },
    { q: "A book containing maps is called an:", opts: ["Encyclopedia", "Almanac", "Atlas", "Index"], ans: 2 },
    { q: "Who is the head of a university library?", opts: ["Chief Librarian / University Librarian", "Vice Chancellor", "Dean of Students", "Chief Cataloguer"], ans: 0 },
    { q: "If a book you need is currently borrowed by someone else, you can place a:", opts: ["Hold / Reservation", "Fine", "Order", "Query"], ans: 0 },
    { q: "Which reference book provides annual data, statistics, and facts?", opts: ["Dictionary", "Almanac", "Atlas", "Manual"], ans: 1 },
    { q: "The process of assigning a specific number to a book so it can be located on the shelf is called:", opts: ["Cataloguing", "Classification", "Indexing", "Binding"], ans: 1 },
    { q: "The place in the library where you check out and return books is the:", opts: ["Reference desk", "Circulation desk", "Serials desk", "Security gate"], ans: 1 },
    { q: "What does a call number do?", opts: ["Calls the librarian", "Identifies the book's exact location on the shelf", "Indicates the book's price", "Shows the number of pages"], ans: 1 },
    { q: "An encyclopedia provides:", opts: ["Definitions of words", "Background information and overviews of subjects", "Only maps", "Only statistics"], ans: 1 },
    { q: "Which type of library is designed to serve a specific organization or company?", opts: ["Public library", "Academic library", "Special library", "School library"], ans: 2 },
    { q: "A systematic compilation of words usually arranged alphabetically with their meanings is a:", opts: ["Catalogue", "Dictionary", "Journal", "Thesis"], ans: 1 },
    { q: "Which of the following describes a 'monograph'?", opts: ["A weekly magazine", "A newspaper", "A detailed written study of a single specialized subject", "An online video"], ans: 2 },
    { q: "What is the penalty for returning borrowed library books late?", opts: ["Expulsion", "Overdue fines", "Buying the book", "No penalty"], ans: 1 },
    { q: "ISSN is uniquely assigned to:", opts: ["Books", "Serials and Periodicals", "Maps", "DVDs"], ans: 1 },
    { q: "Which section handles the repair of torn or damaged books?", opts: ["Reference", "Circulation", "Bindery", "Acquisition"], ans: 2 },
    { q: "To find the geographical location of a country, you consult a/an:", opts: ["Dictionary", "Atlas", "Encyclopedia", "Directory"], ans: 1 }
];
